services:

  postgres-db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=plagapp-db
    ports:
      - 5432:5432
    networks:
      - flask-app

  plagapp:
    build: 
      context:  .
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres-db
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=plagapp-db
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=2444666668888888
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flask-app

networks:
  flask-app:

volumes:
  pgdata: ~